In [23]:
#Importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [24]:
#Importing the dataset
data = pd.read_csv('train_file.dat', delimiter = "	", quoting = 3, header = None)
df = pd.DataFrame(data)

In [25]:
#Cleaning the dataset
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 18506):
    review = re.sub('[^a-zA-Z]', ' ', str(df[1][i]))
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    allStop = stopwords.words('english')
    allStop.remove('not')
    review = [ps.stem(word) for word in review if not word in set(allStop)]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/darrylanthony/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [26]:
#Creating the bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y = df.iloc[:, 0].values

In [27]:
#Applying TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus).toarray()

In [28]:
len(X[0])

14859

In [29]:
#Splitting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [30]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='lbfgs')
lr.fit(X_train, y_train)

LogisticRegression()

In [31]:
y_pred = lr.predict(X_test)

In [32]:
print(y_pred)

[ 1  1 -1 ...  1  1 -1]


In [33]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1458  257]
 [ 210 1777]]


0.8738519719070773

In [34]:
#Checking on the whole training dataset
new_pred = lr.predict(X)

In [35]:
print(new_pred)

[ 1  1  1 ... -1 -1 -1]


In [36]:
#Checking the accuracy of the model
from sklearn.metrics import confusion_matrix, accuracy_score
cm2 = confusion_matrix(y, new_pred)
print(cm2)
accuracy_score(y,new_pred)

[[7522  984]
 [ 871 9129]]


0.8997622392737491

In [37]:
#Importing the test dataset
test = pd.read_csv('test.dat', delimiter = "\t", header=None, quoting = 3, skip_blank_lines=False)
df2 = pd.DataFrame(test)

In [38]:
print(df2)

                                                       0
0      Perfect for new parents. We were able to keep ...
1      Helps me know exactly how my babies day has go...
2      I wanted an alternative to printing out daily ...
3      My 3 month old son spend half of his days with...
4      The Baby Tracker brand books are the absolute ...
...                                                  ...
18501  WTF. The pieces don't fit together, the instru...
18502  I've gone through a couple of video baby monit...
18503  This monitor is cheap and doesn't work well. O...
18504  These monitors do not work at all, I even atte...
18505  Short story, I was very disappointed with the ...

[18506 rows x 1 columns]


In [39]:
#Cleaning the dataset
corpus2 = []
for i in range(0, 18506):
    review = re.sub('[^a-zA-Z]', ' ', str(df2[0][i]))
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    allStop = stopwords.words('english')
    allStop.remove('not')
    review = [ps.stem(word) for word in review if not word in set(allStop)]
    review = ' '.join(review)
    corpus2.append(review)

In [40]:
#Converting to vector representation
X_ = cv.transform(corpus2).toarray()

In [41]:
len(X_[0])

14859

In [42]:
#Prediction on the test file
Y_Pred = lr.predict(X_)

In [44]:
#Write the prediction file to another file
Y_Pred.tofile('pred7.dat', sep = '\n')